import 'package:get/get.dart';

class Localization extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'DashBoard':'DashBoard',
          'Log Out':'Log Out',
          'Kaundia Madrasha':'Kaundia Madrasha',
          'My Profile': 'My Profile',
          'Add Students': 'Add Students',
          'Save':'Save',
          'View Students': 'View Students',
          'Pay Tuition Fees': 'Pay Tuition Fees',
          'Users': 'Users',
          'Settings': 'Settings',
          'Report': 'Report',
          'Change Language': 'Change Language',
          'Change Theme': 'Change Theme',
          'All Classes': 'All Classes',
          'Class': 'Class',
          'Roll': 'Roll',
          'Student Name':'Student Name',
          'Father Name': 'Father Name',
          'Mother Name': 'Mother Name',
          'Address': 'Address',
          'Phone': 'Phone',
          'Session': 'Session',
          'Date Of Birth': 'Date Of Birth',
          'Select Class': 'Select Class',
          'Select Date': 'Select Date',
          'No Date Chosen': 'No Date Chosen'
        },
        'bn_BD': {
          'DashBoard':'ড্যাশবোর্ড',
          'Log Out':'লগ আউট',
          'Kaundia Madrasha':'কাউন্দিয়া মাদরাসা',
          'My Profile': 'আমার প্রোফাইল',
          'Add Students': 'শিক্ষার্থী যোগ করুন',
          'Save':'সংরক্ষণ',
          'View Students': 'শিক্ষার্থী দেখুন',
          'Pay Tuition Fees': 'টিউশন ফি প্রদান',
          'Users': 'ব্যবহারকারি',
          'Settings': 'সেটিংস',
          'Report': 'রিপোর্ট',
          'Change Language': 'ভাষা পরিবর্তন',
          'Change Theme': 'থিম পরিবর্তন',
          'All Classes': 'সকল শ্রেণী',
          'Class': 'শ্রেণী',
          'Roll': 'রোল',
          'Student Name':'শিক্ষার্থীর নাম',
          'Father Name': 'বাবার নাম',
          'Mother Name': 'মায়ের নাম',
          'Address': 'ঠিকানা',
          'Phone': 'ফোন',
          'Session': 'সেশন',
          'Date Of Birth': 'জন্ম তারিখ',
          'Select Class': 'শ্রেণী নির্বাচন করুন',
          'Select Date': 'তারিখ যোগ করুন',
          'No Date Chosen': 'কোনো তারিখ বেছে নেওয়া হয়নি',
        },
      };
}
