// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtZfTvnBaAzyAIe5lPo5LM0GW00EB8lm8',
    appId: '1:826170491178:web:a329aceccc90a4aee79e53',
    messagingSenderId: '826170491178',
    projectId: 'my-project-2a81a',
    authDomain: 'my-project-2a81a.firebaseapp.com',
    storageBucket: 'my-project-2a81a.appspot.com',
    measurementId: 'G-VRDCY25JLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1GTXsDe5t-Al9ijyZcRxvBm7TKseQrlo',
    appId: '1:826170491178:android:9d88840bef83ae33e79e53',
    messagingSenderId: '826170491178',
    projectId: 'my-project-2a81a',
    storageBucket: 'my-project-2a81a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtHD2R7nfRtz9EqQCjuUYhjBqeJRvPqL0',
    appId: '1:826170491178:ios:75e0c69cf7afd34ae79e53',
    messagingSenderId: '826170491178',
    projectId: 'my-project-2a81a',
    storageBucket: 'my-project-2a81a.appspot.com',
    androidClientId: '826170491178-3nphbjkumariarg29i0r5aot31vuso1j.apps.googleusercontent.com',
    iosClientId: '826170491178-hlvanemciu6tad7falevb52sgbac7drb.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentManagement',
  );
}
